name: Cypress Tests 🧪 - all-tests.yml

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          working-directory: .
          component: true

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start

