name: Cypress Tests - main.yml

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run --component

      - name: Run E2E tests 🧪
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start