name: Run Component tests 🧪 - teste.yml
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          working-directory: .
          component: true
